name: Deploy to GCP

on:
  push:
    branches:
      #- main
      - feature/github-actions-deploy

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy the application
      - name: Deploy to GCP
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} << EOF
          set -x
          sudo su - deploy -c "
            cd /var/www/prj/platform-core &&
            docker compose -f docker-compose.dev.yml down &&
            git pull origin feature/github-actions-deploy &&
            docker compose -f docker-compose.dev.yml up --build -d
          "
          EOF
      
      # Step 4: Cleanup
      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up temporary files..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          docker system prune -f
          EOF
