# docker-compose.yml

services:
  pgsql:
    image: postgis/postgis:17-3.5
    env_file:
      - .env  # Load environment variables from a .env file
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - platformcore-network

  platformcore:
    build: .
    env_file:
      - .env  # Load environment variables from a .env file
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgsql
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - platformcore-network
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - platformcore-network
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    ports:
      - "5601:5601"  # Default Kibana port
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    networks:
      - platformcore-network

volumes:
  pgdata:

networks:
  platformcore-network: