version: "3.9"
services:
    traefik:
        image: traefik:v2.10
        container_name: traefik
        restart: always
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./traefik.yml:/etc/traefik/traefik.yml:ro
            - ./castom/:/etc/traefik/custom/:ro
            - type: bind
              source: ./acme.json
              target: /etc/traefik/acme.json

networks:
    default:
        external: true
        name: nginx_net
